name: "Link Updater"
description: "Automatically updates repository links/keywords and optionally creates PRs"
author: "vikshan"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}

  CONFIG_PATH:
    description: "Path to the links-config.yml configuration file"
    required: false
    default: ".github/links-config.yml"

runs:
  using: "composite"
  steps:
    - name: Setup Bun and install dependencies
      uses: iamvikshan/.github/.github/actions/bun-actions@main
      with:
        working-directory: ${{ github.action_path }}

    - name: Run link updater
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_CONFIG_PATH: ${{ inputs.CONFIG_PATH }}
      run: bun run ${{ github.action_path }}/src/index.ts

    - name: Post-Job Cleanup
      if: always()
      shell: bash
      run: bun ${{ github.action_path }}/scripts/postjob.ts

branding:
  icon: "link"
  color: "blue"
