name: "Link Updater"
description: "Automatically updates repository links and optionally creates PRs"
author: "vikshan"

inputs:
  token:
    description: "GitHub token for authentication"
    required: true
    default: ${{ github.token }}

  config-path:
    description: "Path to the updatelinks.yml configuration file"
    required: false
    default: ".github/updatelinks.yml"

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install specific dependencies
      shell: bash
      run: |
        echo '{
          "dependencies": {
            "@actions/core": "^1.10.0",
            "@actions/github": "^5.1.1",
            "@actions/exec": "^1.1.1",
            "js-yaml": "^4.1.0"
          }
        }' > package.json
        bun install

    - name: Run link updater
      shell: bash
      run: bun run ${{ github.action_path }}/dist/index.js
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
        INPUT_CREATE_PR: ${{ inputs.create-pr }}

branding:
  icon: "link"
  color: "blue"
