name: 'Repository Link Updater'
description: 'Automatically updates repository links based on configuration file'
author: 'vikshan'

inputs:
  token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
  
  config-path:
    description: 'Path to the updatelinks.yml configuration file'
    required: false
    default: '.github/updatelinks.yml'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'link'
  color: 'blue'