name: "Link Updater"
description: "Automatically updates repository links/keywords and optionally creates PRs"
author: "vikshan"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}

  CONFIG_PATH:
    description: "Path to the links-config.yml configuration file"
    required: false
    default: ".github/links-config.yml"

runs:
  using: "composite"
  steps:
    - name: Backup Original Project Dependencies
      shell: bash
      run: |
        # Backup existing package.json and bun.lock if they exist
        if [ -f package.json ]; then
          cp package.json package.json.original-backup
        fi
        if [ -f bun.lock ]; then
          cp bun.lock bun.lock.original-backup
        fi

    - name: Create Minimal Dependencies Package
      shell: bash
      run: |
        # Create a minimal package.json with only required dependencies
        echo '{
          "dependencies": {
                    "@actions/core": "^1.11.1",
                    "@actions/exec": "^1.1.1",
                    "@actions/github": "^6.0.1",
                    "js-yaml": "^4.1.0"
          }' > package.json

    - name: Setup Bun and install dependencies
      uses: iamvikshan/.github/.github/actions/setup-bun@main

    - name: Run link updater
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_CONFIG_PATH: ${{ inputs.CONFIG_PATH }}
      run: bun run ${{ github.action_path }}/src/index.ts

    - name: Post-Job Cleanup
      if: always()
      shell: bash
      run: bun ${{ github.action_path }}/scripts/postjob.ts

branding:
  icon: "link"
  color: "blue"
