name: Build CI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build TypeScript
        run: bun run build

      - name: Build package
        run: bun run package

      - name: Publish package
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ':rocket: Deploy new version [skip ci]'
          commit_user_name: Koj Bot
          commit_user_email: bot@koj.co
          commit_author: Koj Bot <bot@koj.co>