name: Test CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Deploy new version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: ./
        with:
          milliseconds: 1000
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

